### ISSUE TITLE
Incompatibe with Bundler >= 1.0.8

### ISSUE THREAD

**Issue by jweir** [engineyard/eycap#19]
Bundler has a Capistrano task which sets rake to `bundle exec rake`

https://github.com/carlhuda/bundler/blob/1-0-stable/lib/bundler/capistrano.rb#L10

If a Gemfile is present Eycap prepends 'bundle exec' to the rake variable. See:
https://github.com/engineyard/eycap/blob/master/lib/eycap/recipes/deploy.rb#L57

If eycap is used with bundler/capistrano the resulting command is `bundle exec bundle exec rake`.  Oy.

**Comment by 7hunderbird** [comment]
Tracking internally with ticket M-159.

**Comment by 7hunderbird** [comment]
This was fixed in v0.5.17 and above eycap.  

See this commit => https://github.com/engineyard/eycap/commit/fb260c302358aaef2974dbb45c8e02d7a0719104

I will be using Jeff LaBarge's (jefflab) comments and notes on that commit to also refactor the redundant useless if/then statement in an upcoming eycap build.

**Comment by 7hunderbird** [comment]
This will be shipped out in the next eycap build => https://github.com/engineyard/eycap/blob/M-159-BundlerCompatibility/lib/eycap/recipes/deploy.rb#L57
